# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2ad48b0d2742e7e53cfc6983e9b670b973040178b61763401eac8285c6eb9a2fd314ae026771aff95e4cb7d57ea9b5c2c46d6116a883bf2801d7fdcca3e8fab

test:
  secret_key_base: 32268414c9a462df951574558b5f358772ee8c371f630d5dc4c83de93fb2e584f89eed1c57068a610f485c574263342295d6a31d975a2ddeeb4ee3c64295e7ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
